enligne/urls.py
from django.conf.urls import include, url
from django.urls import path

urlpatterns = [
    path('', include('utiliser.urls', namespace="utiliser")),
]

utiliser/urls.py
from django.conf.urls import url

from . import views

app_name = "utiliser"

urlpatterns = [
    url(r'^$', views.choix, name="choix"),
    url(r'^creer/', views.creer, name="creer"),
    ]

utiliser/models.py
from django.db import models

# Create your models here.

utiliser/views.py
import functools
import itertools
import os

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse

from pyromaths.ex import ExerciseBag
from pyromaths.outils.System import Fiche
from pyromaths.version import VERSION

from datetime import date

from . import MAINSITEURL

BAG = ExerciseBag()
EXERCICES = [
        (
            niveau,
            [(exo.name(), exo.description()) for exo in exercices]
        )
        for niveau, exercices in BAG.sorted_levels()
        ]

def choix(request):
    return render(request, 'utiliser/utiliser.html', {
        'VERSION': VERSION,
        'DOWNLOADURL': VERSION.replace('.', '-'),
        'EXERCICES': EXERCICES,
        'MAINSITEURL': MAINSITEURL,
        'deficit': 1888.98+11.99*(date.today().year*12 + date.today().month-12*2014-6)
        }
        )

def _first(length=1):
    def decorator_first(func):
        @functools.wraps(func)
        def wrapper_first(*args, **kwargs):
            return itertools.islice(func(*args, **kwargs), length)
        return wrapper_first
    return decorator_first

@_first(5)
def parseSeeds(*arguments):
    """Itérateur sur (au maximum) cinq 'seeds' d'exercice."""
    for argument in arguments:
        for text in argument.split(","):
            try:
                yield int(text)
            except ValueError:
                pass

def creer(request):
    # Génération de la liste d'exercices
    exercices = []
    for key in request.GET:
        if key in BAG:
            for seed in parseSeeds(*request.GET.getlist(key)):
                exercices.append(BAG[key](seed))
    # Génération du PDF
    if exercices:
        parametres = {
            'enonce': True,
            'corrige': True,
            'exercices': exercices,
            'titre': "Fiche de révisions",
            }
        with Fiche(parametres) as fiche:
            fiche.write_pdf()

            # Envoi du PDF
            with open(fiche.pdfname, mode="rb") as pdf:
                response = HttpResponse(content_type = 'application/pdf')
                response['Content-Disposition'] = 'attachment; filename=exercices.pdf'
                response['Content-Length'] = os.path.getsize(fiche.pdfname)
                response.write(pdf.read())
                return response
    else:
        messages.error(request, "Vous devez sélectionner au moins un exercice.")
        return redirect("utiliser:choix")

utiliser/templates/utiliser/deuxcolonnes.html
{% extends "utiliser/layout.html" %}

{% block content %}
<div id="deux_cols">
    <div id="col_droite">
        {% block colonnedroite %} {% endblock %}
    </div>

    <div id="col_gauche">
        {% block colonnegauche %} {% endblock %}
    </div>

    <div class="clear"></div>
</div>
{% endblock %}

utiliser/templates/utiliser/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
  <title>{% block title %}{% endblock %}</title>

  {% block head %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel="icon" href="{{ MAINSITEURL }}/theme/images/favicon.ico"/>
  <link rel="stylesheet" href="{{ MAINSITEURL }}/theme/css/style.css" type="text/css"/>
  {% endblock head %}

  {% block javascript %}{% endblock %}
</head>

<body>
<div id="total">
  <div id="page">
    <div id="header">
      {% block header %}
      <div id="logo_holder">
          <h1><a href="{{ MAINSITEURL }}" id="logo">Pyromaths</a></h1>
      </div>

      <div class="topnav" id="nav_menu">
        <a href="javascript:void(0);" class="icon" onclick="myFunction();">
          <!--<i class="fa fa-bars"></i>-->
        </a>
        <ul>
          <li><a href="{{ MAINSITEURL }}" class="active">Accueil</a></li>
          <li><a href="https://enligne.pyromaths.org/">Utiliser en ligne</a></li>
	  <li><a href="{{ MAINSITEURL }}/version-{{ DOWNLOADURL }}.html">Télécharger</a></li>
          <li><a href="{{ MAINSITEURL }}/installer-pyromaths.html">Documentation</a></li>
          <li><a href="http://pyromaths.readthedocs.io">Développeurs</a></li>
          <li id="adroite"><a href="https://forum.pyromaths.org">Forum</a></li>
        </ul>
      </div>
      <script>
      function myFunction() {
        var x = document.getElementById("nav_menu");
        if (x.className === "topnav") {
          x.className += " responsive";
        } else {
          x.className = "topnav";
        }
      }
      </script>
      {% endblock header %}
    </div>

    {% block content %}{% endblock %}

  </div><!--page-->
  <div id="footer">
    <div id="copyright">
      <p>&copy; 2018 Pyromaths<br/>
        Thème inspiré d'un travail de <a href="https://www.divio.ch/">Divio GmbH</a></p>
    </div>
  </div>
</div> <!--total-->
</body>
</html>

utiliser/templates/utiliser/utiliser.html
{% extends "utiliser/deuxcolonnes.html" %}
{% load static %}
{% block title %}Pyromaths en ligne, un générateur de fiches d’exercices{% endblock %}
{% block javascript %}
<!--<link rel="stylesheet" href="{% static "enligne-original.css" %}">-->
<script src="{% static "js/jquery-1.10.2.js" %}"></script>
<script src="{% static "js/jquery-ui-1.10.4.custom.min.js" %}"></script>
{% endblock %}

{% block colonnegauche %}
<h5>{{ VERSION }}</h5>
<h1>Utiliser Pyromaths en ligne</h1>
<script type="text/javascript">
  $(function() {
  $("#tabs").tabs();
});
</script>


{% if messages %}
<ul class="messages" id="errmsg">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div id="tabs">
  <ul>
  {% for niveau, exercices in EXERCICES %}
    <li><a href="#tabs-{{ forloop.counter0 }}">{{ niveau }}</a></li>
  {% endfor %}
  </ul>

  {% for niveau, exercices in EXERCICES %}
  <div id="tabs-{{ forloop.counter0 }}">
    <table class="tabs">
      {% for name, description in exercices %}
        {% if forloop.counter0|divisibleby:2 %}<tr>{% endif %}
        <td>
            <select id="ex-{{ name }}">
                <option selected="selected">0</option>
                <option>1</option>
                <option>2</option>
                <option>3</option>
                <option>4</option>
                <option>5</option>
            </select>
            {{ description }}
        </td>
        {% if not forloop.counter0|divisibleby:2 %}</tr>{% endif %}
  {% endfor %}
    </table>
  </div>
  {% endfor %}
  <form method="get" action="{% url 'utiliser:creer' %}" id="idForm" onsubmit="return ray.ajax()">
    {% csrf_token %}
    <noscript>L'utilisation de Pyromaths en ligne nécessite l'activation de Javascript.</noscript>
    <p>
      <br/>
      <input type="submit" value="Cr&eacute;er" />
      <input type="reset" value="Annuler" />
    </p>
  </form>
  <script type="text/javascript">
    $body = $("body");
    var ray={
      ajax:function(st)
      {
        $body.addClass("loading");
      }
    };
  </script>
</div>

<script>
var exolist = [
  {% for niveau, exercices in EXERCICES %}
      {% for name, description in exercices %}
        "{{ name }}"{% if not forloop.last or not forloop.parentloop.last %},{% endif %}
      {% endfor %}
  {% endfor %}
  ];
function generateSeeds(count) {
  seeds = [];
  for(; count > 0; count--){
    seeds.push(Math.floor((Math.random() * 1000000000) + 1));
  }
  return seeds.join(",");
}
$('#idForm').submit(function(){ //listen for submit event
    $('#idForm').children(".seed").remove();
    $.each(exolist, function(i,exo){
      count = Number($("#ex-" + exo + " :selected").text());
      if (count) {
        $('<input />').attr('type', 'hidden')
            .attr('name', exo)
            .attr('class', 'seed')
            .attr('value', generateSeeds(count))
            .appendTo('#idForm');
      }
    });

    return true;
}); 
</script>
{% endblock %}

{% block colonnedroite %}
<p>Le site de <strong>Pyromaths</strong> vous permet de générer une fiche
d'exercices avec le corrigé sur une page à part au format
pdf sans installer aucun programme sur votre ordinateur. Il vous suffit juste de
disposer d'un lecteur pdf.</p>
<p>Pour permettre cela, il nous a fallu louer un serveur dédié afin de pouvoir
y installer Python et LaTeX. La location de ce serveur a coûté 35,87&#160;€ TTC
par mois jusqu'en juin 2010, 17,93&#160;€ TTC jusqu'en avril 2013, 11,95&#160;€
TTC jusqu'en décembre 2013. Depuis cette date, nous louons un serveur à
11,99&#160;€ TTC par mois. Nous avons besoin d'aide pour le financer.</p>
<p>En effet, depuis février 2008, ce serveur nous a coûté <strong>
    {{ deficit|floatformat:"2" }}&#160;€</strong></p>
<p>En cliquant sur le lien ci-dessous, vous pourrez participer à ces frais. Nous
vous remercions.</p>
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
    <p>
    <input type="hidden" name="cmd" value="_s-xclick"/>
    <input type="hidden" name="hosted_button_id" value="5486963"/>
    <input type="image"
    src="https://www.paypal.com/fr_FR/FR/i/btn/btn_donate_SM.gif"
    name="submit" alt="PayPal"/>
    <img alt="logo Paypal"
    src="https://www.paypal.com/fr_FR/i/scr/pixel.gif"/>
    </p>
</form>

{% endblock %}